const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.JSDOM_PATH||'jsdom');
const file=process.argv[2]||__dirname+'/prototype-screen1-work-c1.html';const html=fs.readFileSync(file,'utf8');let pass=0;
function app(saved,device={}){let jobs=new Map(),next=0,errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://screen1-test.invalid/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.matchMedia=q=>({matches:q.includes('hover:hover')||q.includes('pointer:fine'),addEventListener(){},removeEventListener(){}});Object.defineProperty(w.navigator,'maxTouchPoints',{value:device.touch||0});if(device.ua)Object.defineProperty(w.navigator,'userAgent',{value:device.ua});w.ResizeObserver=class{observe(){}};w.scrollTo=()=>{};w.requestAnimationFrame=f=>{f();return 1};w.setTimeout=f=>{jobs.set(++next,f);return next};w.clearTimeout=id=>jobs.delete(id);if(saved)w.sessionStorage.setItem('rodeni-work-screen1-c1',JSON.stringify(saved))}});const w=dom.window,$=id=>w.document.getElementById(id);return {w,$,dom,errors,click:id=>$(id).click(),set(id,value){$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}))},flush(){const a=[...jobs.values()];jobs.clear();a.forEach(f=>f())},jobs};}
function check(name,fn){const a=app();try{fn(a);assert.deepEqual(a.errors,[]);console.log('PASS '+name);pass++}finally{a.dom.window.close()}}
function current(a,country,city){a.click('start');a.set('country',country);a.set('current',city);a.click('next')}
function result(a,country,city,root){current(a,country,city);a.set('root',root);a.click('next');a.flush()}
for(const script of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new Function(script[1]);
const ids=[...html.replace(/<script>[\s\S]*?<\/script>/g,'').matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);assert(!/\bfetch\s*\(|supabase|<script[^>]+src=/i.test(html));console.log('PASS syntax, static IDs, no remote scripts/backend');pass++;
check('initial: public entry, no restored markers',a=>{assert(a.$('panel').hidden);assert(!a.w.document.body.classList.contains('flow'));assert(a.$('start').textContent.includes('Провери'));});
check('validation: cannot advance without canonical Current',a=>{a.click('start');a.click('next');assert(!a.$('error').hidden);a.set('country','DE');a.set('current','непознато');a.click('next');assert.equal(a.$('question').textContent,'Къде си сега?')});
check('Munich + Lom exact 25+',a=>{result(a,'DE','Мюнхен','Лом');assert.equal(a.w.document.querySelector('.band').textContent,'25+');assert.equal(a.w.document.querySelector('.kind').textContent,'За двете ти места')});
check('Paris + Kovachitsa broader 5+',a=>{result(a,'FR','Париж','Ковачица');assert.equal(a.w.document.querySelector('.band').textContent,'5+');assert(a.$('content').textContent.includes('не точната комбинация'));});
check('Paris + Sofia must NOT return Lom broader',a=>{result(a,'FR','Париж','София');assert.equal(a.w.document.querySelector('.band'),null);assert(!a.$('content').textContent.includes('от Лом и региона'));});
check('Graz + Sofia suppressed, no count',a=>{result(a,'AT','Грац','София');assert.equal(a.w.document.querySelector('.band'),null);assert(a.$('content').textContent.includes('Малките групи'));});
check('all offered localities have finite coordinates',a=>{assert(a.w.eval('places.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))'));for(const city of ['Кьолн','Франкфурт','Нюрнберг'])assert(a.w.eval('find('+JSON.stringify('DE|'+city)+').y < 120'));});
check('close during loading cancels pending completion',a=>{current(a,'DE','Мюнхен');a.set('root','Лом');a.click('next');const late=[...a.jobs.values()];a.click('close');a.flush();late.forEach(f=>f());assert(a.$('panel').hidden);assert(!a.w.document.body.classList.contains('flow'));a.click('start');assert.equal(a.$('question').textContent,'Откъде си?')});
check('change during loading ignores stale result',a=>{current(a,'DE','Мюнхен');a.set('root','Лом');a.click('next');const late=[...a.jobs.values()];a.click('back');late.forEach(f=>f());assert.equal(a.$('question').textContent,'Къде си сега?')});
check('temporary error retries same context successfully',a=>{a.set('network','once');result(a,'DE','Мюнхен','Лом');assert(a.$('retry'));assert(!a.$('skip'));a.click('retry');a.flush();assert.equal(a.w.document.querySelector('.band').textContent,'25+')});
check('persistent error permits skip only after retry, resets on edit',a=>{a.set('network','fail');result(a,'DE','Мюнхен','Лом');assert(!a.$('skip'));a.click('retry');a.flush();assert(a.$('skip'));a.click('skip');assert(a.$('content').textContent.includes('Профил не се създава'));a.click('return');a.click('back');a.set('current','Берлин');a.click('next');a.set('root','Лом');a.click('next');a.flush();assert(!a.$('skip'))});
check('fallback Stuttgart + Ruse survives reload, clean initial',a=>{a.click('start');a.set('country','DE');a.set('current','Щутгарт');a.click('missing');a.click('lookup');a.click('next');a.set('root','Русе');a.click('missing');a.click('lookup');a.click('next');a.flush();const saved=JSON.parse(a.w.sessionStorage.getItem('rodeni-work-screen1-c1'));const b=app(saved);try{assert(b.$('panel').hidden);b.click('start');assert.equal(b.$('root').value,'Русе');assert(b.$('content').textContent.includes('Щутгарт'));assert.deepEqual(b.errors,[])}finally{b.dom.window.close()}});
check('unverified Root permits honestly labeled Current-only result',a=>{current(a,'FR','Париж');a.set('root','Непознато село');a.click('missing');a.click('lookup');assert(!a.$('unverified').hidden);a.click('unverified');a.flush();assert.equal(a.w.document.querySelector('.kind').textContent,'Само според „Сега“');assert(a.$('mapCaption').textContent.includes('непотвърдено'));});
check('resolver outage differs from no match and preserves input',a=>{a.set('resolver','fail');current(a,'FR','Париж');a.set('root','Русе');a.click('missing');a.click('lookup');assert(a.$('lookupError').textContent.includes('временно е недостъпно'));assert.equal(a.$('root').value,'Русе')});
check('whitespace normalization and escaped unverified text',a=>{assert.equal(a.w.eval('norm("  Велико   Търново ")'),'велико търново');current(a,'FR','Париж');a.set('root','<img src=x onerror=alert(1)>');a.click('missing');a.click('lookup');a.click('unverified');a.flush();assert.equal(a.$('content').querySelector('img'),null)});
for(const d of [{version:1,country:'XX',current:'bad',updated:Date.now()},{version:1,country:'DE',current:'DE|Мюнхен',updated:Date.now()-86400001}]){const a=app(d);a.click('start');assert.equal(a.$('country').value,'');assert(a.$('content').textContent.includes('не може да се възстанови'));a.dom.window.close()}console.log('PASS invalid/expired session recovery');pass++;
const mobile=app(null,{touch:1,ua:'Mozilla/5.0 (Linux; Android 16)'});assert(mobile.w.document.documentElement.classList.contains('force-mobile'));mobile.dom.window.close();console.log('PASS force-mobile Android/touch');pass++;
console.log('TOTAL '+pass+' groups PASS. DOM simulation only: no browser layout, screenshot or visual PASS.');
